# -*- coding: utf-8 -*-
"""python basic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VQwu1CYRroCJ7K2du1wL6_TKAvCDBYzR
"""

print("hello")

print("hello"+ "world")

print("hello"+" " + "world")

print(hello); # error

12*10

print( type(12))

print( type(12,12.3)) # error

age =14
print( (age%5 ==0 and age%7 ==0) or age%7 ==0 )

age =14
print( (age%5 ==0 and age%7 ==0) and not age%9==0 )

age =14
print( age%5 ==0 or age%7 ==0)

age =14
print( age%5 ==0 and age%7 ==0)

age =14
print( age%5 ==0, age%7 ==0)

### 3.1)

print( 12//False) # error

print('hello')

print('hello', end = ' ')
print('world')

print('hello', end = '/n ')
print('world')

print('hello', end = '\n')
print('world')

"""not forward slash"""

print('hello', end = '\n')
print('world')

print("Hello"); print("World")

print("Hello", end = ' '); print("World")

print(1+\
      2+\
      3);

n =9
if(n>8):
  print("9")
print("tring")
if True:
  print(6)

print(type(345))
print(type('23'))

print( "hello \"")

print( "hello \"", "\'")

print("\u2756")

print(chr(65))

print("\b")
print("\r")
print("\a")
print(345,'\'')

print("a", end="-")
print("b", end="-")
print("c", end="-")

print('a', 'b', 'c', sep ='-----')

print(4>=3)

print(4=>3) #error

print(3.4*'hello')  #error

print(3*'hello')
print('hello'*4)