
# Some advance questions
 #1 list the top 5 cuisines as per the revenue generaated by top 5 restaurants of every cuisine

 select * from (select * from (select *, cost* rating_count as 'revenue',
 row_number() over(partition by cuisine order by cost* rating_count desc) 
 as 'row_rank' from restaurants) as T1  
 where T1.row_rank<6) as T2 where t2.row_rank<2 limit 5 ;
 
 
 # window function + group by clouse
select cuisine, sum(revenue) as ' t_revenue', row_rank from (select *, cost* rating_count as 'revenue', row_number() 
over(partition by cuisine order by cost* rating_count desc) 
as 'row_rank' from restaurants) as T1  
where T1.row_rank<6  group by cuisine order by t_revenue desc limit 5  ;
 
 
 #2 what % of the total revenue generated by top 1% restaurants
 select * from (select name, sum(cost* rating_count) as 'revenue' from restaurants 
 group by name order by revenue desc) as t ;
 -- 1% of total restaurants
 (select round((1* count(*))/100,0) from restaurants);
 
 -- 1% of distinct restaurants
 select round((1* count(*))/100,0)  from (select name, sum(cost* rating_count) as 'revenue' from restaurants 
 group by name order by revenue desc)  as T1;
   
  
 select sum(revenue)  from (select * from (select name, sum(cost* rating_count) as 'revenue' from restaurants 
 group by name order by revenue desc) as T1  limit 5) as t2;
 
 # using window function
select sum(revenue) from (select *, cost* rating_count as 'revenue', row_number() 
over( order by cost* rating_count desc) as 'row_rank' from restaurants) as T1 
where T1.row_rank <= ((select round((count(*) *1)/100) from restaurants));    
 
select sum(cost* rating_count) from restaurants;     
select (462914000/2647814350)*100;
-- conclusion == top 1 % restraunts generate 17 % of total revenue
   
 #3 check the same for 20% restaurants
 select sum(revenue) from (select *, cost* rating_count as 'revenue', row_number() 
over( order by cost* rating_count desc) as 'row_rank' from restaurants) as T1 
where T1.row_rank <= ((select round((count(*) *20)/100) from restaurants));   
 select (1988088100/2647814350)*100;
  -- conclusion == top 20 % restraunts generate 75 % of total revenue

 #4 what % of revenue is generated by top 20% of restaurants with respect to total revenue?
 select ((select sum(revenue) from (select *, cost* rating_count as 'revenue', row_number() 
over( order by cost* rating_count desc) as 'row_rank' from restaurants) as T1 
where T1.row_rank <= ((select round((count(*) *20)/100) from restaurants)))/(select sum(cost* rating_count) from restaurants))*100; 

# Using with clouse
with 
x1 as (select sum(revenue) as '20_revenue' from (select *, cost* rating_count as 'revenue', row_number() 
over( order by cost* rating_count desc) as 'row_rank' from restaurants) as T1 
where T1.row_rank <= ((select round((count(*) *20)/100) from restaurants))),

x2 as (select sum(cost* rating_count) as 'total_revenue' from restaurants)

select (20_revenue/ total_revenue)*100 as 'revenue' from x1,x2;